/**
 * Authorizer function tests.
 *
 * Generated by serverless-mocha-plugin.
 *
 * @module tests/authorizer
 */

const UNAUTHORIZED = 'Unauthorized';

const mochaPlugin = require('serverless-mocha-plugin');

const wrapped = mochaPlugin.getWrapper('authorizer', '/service/functions/authorizer.js', 'handler');
const expect = mochaPlugin.chai.expect;

describe('authorizer', () => {
  it('should not authorize a user without a token', () =>
    wrapped
      .run({
        headers: {}
      })

      .then(response => expect(response).to.be.empty)

      .catch(err => expect(err).to.equal(UNAUTHORIZED)));

  it('should not authorize a user with an invalid a token', () =>
    wrapped
      .run({
        headers: {
          Authorization: 'im-invalid-lol'
        }
      })

      .then(response => expect(response).to.be.empty)

      .catch(err => expect(err).to.equal(UNAUTHORIZED)));
});
