/**
 * Authorizer function tests.
 *
 * Generated by serverless-mocha-plugin.
 *
 * @module tests/authorizer
 */

const mochaPlugin = require('serverless-mocha-plugin');

const jwtToken = require('./jwt-token.json'); // ["jwt-or-id-token"]

const wrapped = mochaPlugin.getWrapper('authorizer', '/service/functions/authorizer.js', 'handler');
const expect = mochaPlugin.chai.expect;

describe('authorizer', () => {
  it('should not authorize a user without a token', async () => {
    try {
      const res = await wrapped.run({
        headers: {}
      });

      expect(res).to.be.empty;
    } catch (err) {
      expect(err).to.equal('Unauthorized');
    }
  });

  it('should not authorize a user with an invalid a token', async () => {
    try {
      const res = await wrapped.run({
        headers: {
          Authorization: 'im-invalid-lol'
        }
      });

      expect(res).to.be.empty;
    } catch (err) {
      expect(err).to.equal('Unauthorized');
    }
  });

  it('should authorize a user with a valid a token', async () => {
    const res = await wrapped.run({
      headers: {
        Authorization: jwtToken[0]
      }
    });

    expect(res).to.not.be.empty;
    expect(res.principalId).to.be.a('string');
    expect(res.context).to.be.an('object');
    expect(res.context.data).to.be.a('string');
  }).timeout(30000);
});
