module.exports = {};

[
  'EMERGENCIES.PERSON_ROBBERY',
  'EMERGENCIES.VEHICLE_ROBBERY',
  'EMERGENCIES.PROPERTY_ROBBERY',
  'EMERGENCIES.DRUG_TRAFFIC',
  'EMERGENCIES.SUSPICIOUS_ACTIVITY',
  'EMERGENCIES.UNREST',
  'EMERGENCIES.OTHER',

  'ENVIRONMENT.LITTERING',
  'ENVIRONMENT.DEBRIS_REPORT',
  'ENVIRONMENT.POLLUTION',
  'ENVIRONMENT.GREEN_AREAS_MAINTENANCE',
  'ENVIRONMENT.GENERAL_MAINTENANCE',
  'ENVIRONMENT.OTHER',

  'SIGNAGE.BROKEN_TRAFFIC_LIGHT',
  'SIGNAGE.POOR_CONDITION',
  'SIGNAGE.ROAD_POOR_CONDITION',
  'SIGNAGE.LUMINARY_POOR_CONDITION',
  'SIGNAGE.SPEED_BUMP_REQUEST',
  'SIGNAGE.OTHER',

  'SERVICES.WATER_OUTAGE',
  'SERVICES.BLACKOUT',
  'SERVICES.MATRIX_BREAK',
  'SERVICES.OTHER_OUTAGE',
  'SERVICES.OTHER',

  'TOWN_HALL.MAYOR_HEARING',
  'TOWN_HALL.COUNCILOR_HEARING',
  'TOWN_HALL.FIELD_VISIT',
  'TOWN_HALL.PERMITS_REQUEST',
  'TOWN_HALL.CONTRIBUTION_REQUEST',
  'TOWN_HALL.OTHER',

  'SOCIAL.ASSISTANT_INTERVIEW',
  'SOCIAL.SERVICES_GRANT',
  'SOCIAL.BONUSES_INFO',
  'SOCIAL.SUPPORT',
  'SOCIAL.EMERGENCY',
  'SOCIAL.OTHER',

  'HEALTH.DOCTORS_APPOINTMENT_REQUEST',
  'HEALTH.BEDRIDDEN_APPOINTMENT_REQUEST',
  'HEALTH.MEDICATION_ASSISTANCE',
  'HEALTH.WORKSHOPS_ENROLLMENT',
  'HEALTH.CONSULTATION_STATUS',
  'HEALTH.PATIENT_ABUSE_REPORT',
  'HEALTH.OTHER',

  'EDUCATION.ENROLLMENT_REQUEST',
  'EDUCATION.SCHOLARSHIP_APPLICATION',
  'EDUCATION.STUDENT_SOCIAL_SUPPORT',
  'EDUCATION.INFRASTRUCTURE_IMPROVEMENT',
  'EDUCATION.TEACHER_INTERVIEW',
  'EDUCATION.OTHER',

  'SPORTS.WORKSHOP_ENROLLMENT',
  'SPORTS.COURT_RENTAL',
  'SPORTS.COURT_MAINTENANCE_REQUEST',
  'SPORTS.GROUPINGS_RESOURCES_REQUEST',
  'SPORTS.OTHER',

  'PETS.LOST',
  'PETS.FOUND',
  'PETS.ABANDONED',
  'PETS.VET_CONSULT',
  'PETS.OTHER',
  'PETS.ANIMAL_ABUSE',

  'TRANSIT.DRIVER_LICENCE',
  'TRANSIT.REGISTERED_FINE',
  'TRANSIT.REGISTRATION_CERTIFICATE',
  'TRANSIT.STREET_RACING',
  'TRANSIT.OTHER',

  'OTHER.OTHER'
].forEach(item => {
  Object.defineProperty(module.exports, item, {
    value: `TAG.${item}`,
    enumerable: true
  });
});
